gdgradzymin/ngPolandConfNext

lib/widgets/drawer.dart
lib/widgets/switchDarkMode.dart

fix sidemenu highlight

---

lib/main.dart
lib/providers/ngGirls.dart
lib/screens/ngGirls.dart
lib/widgets/drawer.dart
pubspec.lock
pubspec.yaml

Data to screen ngGirls is downloaded from api.
Resolves #16

Added content to ngGirls

---

lib/screens/info.dart
lib/widgets/info/navigation.dart

Added navigation in Info

---

lib/screens/home.dart
lib/widgets/home/button.dart
lib/widgets/home/tabs.dart

Added screen Home

---

analysis_options.yaml

analysis_options

---

lib/screens/speakerDetails.dart
lib/screens/speakers.dart
lib/screens/workShops.dart
lib/services/contentful.dart

Resolves #37 
Resolves #38  
Resolves #39

Added workShops, backend to speakers and code fix

---

lib/main.dart
lib/providers/connection.dart
lib/providers/eventItems.dart
lib/providers/infoItems.dart
lib/providers/ngGirls.dart
lib/providers/speakers.dart
lib/providers/workShops.dart
lib/screens/about.dart
lib/screens/home.dart
lib/screens/info.dart
lib/screens/ngGirls.dart
lib/screens/schedule.dart
lib/screens/schedulePresenter.dart
lib/screens/speakerDetails.dart
lib/screens/speakers.dart
lib/screens/workShops.dart
lib/services/contentful.dart
lib/widgets/connection.dart
lib/widgets/schedule/animatedBottomNav.dart
pubspec.lock
pubspec.yaml

Resolves #51 
When the connection lost showed is a red icon and when the user trying fetching data and is offline then show snackbar

Checking connection and showing snackbar

---

lib/main.dart
lib/models/contentful.dart
lib/providers/workShops.dart
lib/screens/about.dart
lib/screens/speakers.dart
lib/screens/workShops.dart
lib/services/contentful.dart
lib/widgets/drawer.dart
lib/widgets/home/tabs.dart
lib/widgets/info/navigation.dart

- different improvements
Resolves: #68

Colors, paddings, file names and some more 🤩

---

lib/screens/schedulePresenter.dart

schedulePresenter improvements

---

lib/main.dart
lib/providers/workShops.dart
lib/screens/schedule.dart
lib/screens/workShops.dart
lib/services/contentful.dart
lib/widgets/schedule/animatedBottomNav.dart

Added backend split workshop on jsPoland, ngPoland

---

lib/main.dart
lib/screens/newHome.dart
lib/screens/ngGirls.dart
lib/screens/schedule.dart
lib/screens/speakerDetails.dart
lib/screens/speakers.dart
lib/widgets/newHome/events.dart
lib/widgets/newHome/timer.dart
lib/widgets/switchDarkMode.dart

- schedule screen final version
- few global theme configuration changes
- some changes in fonts
Resolves #77

Few UI improvements 🚀

---

lib/main.dart
lib/providers/eventItems.dart
lib/providers/workShops.dart
lib/screens/schedule.dart
lib/screens/workShops.dart
lib/widgets/newHome/events.dart
lib/widgets/schedule/animatedBottomNav.dart

Resolves #82
Resolves #83 
Resolves #84

Added (navigators to home, saving selected type) and corrected workshopdetails

---

lib/widgets/schedule/content.dart

Some small schedule improvements

---

android/app/build.gradle
ios/Flutter/AppFrameworkInfo.plist
ios/Flutter/Debug.xcconfig
ios/Flutter/Release.xcconfig
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/contents.xcworkspacedata
lib/main.dart
lib/services/contentful.dart
pubspec.lock
pubspec.yaml

some changes to work with iOS emulator + replacement flutter_config library.
TODO:
- run iOS and android emulator & check if everything ok
- try build and test on physical device in release mode

fixed issue with run ios emulator

---

lib/widgets/schedule/content.dart
lib/widgets/workshops/content.dart

Bugfix data in schedule and workshops

---

lib/main.dart
lib/providers/eventItems.dart
lib/providers/infoItems.dart
lib/providers/ngGirls.dart
lib/providers/speakers.dart
lib/providers/workShops.dart
lib/screens/schedule.dart
lib/screens/speakers.dart
lib/screens/workShops.dart
lib/services/contentful.dart
lib/widgets/info/content.dart
lib/widgets/ngGirls/content.dart

Created one variable for the current conference

---

lib/providers/infoItems.dart
lib/providers/ngGirls.dart
lib/screens/info.dart
lib/screens/ngGirls.dart
lib/services/contentful.dart
lib/widgets/info/content.dart

Switch to 2020 🚀

---

lib/main.dart
lib/screens/about.dart
lib/screens/newHome.dart
lib/widgets/drawer.dart
lib/widgets/info/content.dart
lib/widgets/newHome/timer.dart
lib/widgets/schedule/content.dart
lib/widgets/speakers/content.dart
lib/widgets/workshops/content.dart

- divider color set in the theme global config (resolves #122)
- decreased contrast for the counter on newHome (resolves #123)

Divider and counter colors updated 🌈

---

lib/providers/eventItems.dart
lib/providers/infoItems.dart
lib/providers/speakers.dart
lib/providers/workShops.dart

Corrected getters

---

lib/main.dart
lib/services/contentful.dart
pubspec.lock
pubspec.yaml

Http calls changed to Dio lib

---

lib/widgets/drawer.dart

Fixes to color selected tile on dark mode in menu
